#!/bin/bash

echo 
if [ $# -lt 1 ]
then
	echo "Which project would you like to delete?"
	read project_name
else
	project_name=$1
fi

slink_path=~/.Projects/

echo Excluindo $project_name...


if [ ! -e $slink_path$project_name ]
then
	echo "Error. Project doesn't exist!"
	exit -1
fi

project_path=$(readlink $slink_path$project_name)

opcao="Inválida"

while [ $opcao = "Inválida" ]
do
	echo "Are you sure you want to delete this project? [yes|no] [y|n]"
	read opcao

	case $opcao in
		y|yes)
			rm $slink_path$project_name
			opcao="Válida"
			;;
		n|no)
			exit 0
			;;
		*)
			echo "Digite uma opção válida!"
			opcao="Inválida"
		;;
	esac
done

opcao="Inválida"

while [ $opcao = "Inválida" ]
do
	echo "Would you like to delete $project_name from disk? [yes|no] [v|view]"
	read opcao

	case $opcao in
		y|yes)
			if [ -e "$project_path/src" ]
			then
				rm -r "$project_path/src/"
			fi
			if [ -e "$project_path/headers" ]
			then
				rm -r "$project_path/headers"
			fi
			if [ -e "$project_path/Makefile" ]
			then
				rm "$project_path/Makefile"
			fi
			
			
			echo "Would you like to delete all files and this folder? [yes|no] [y|n]"
			tree $project_path
			#Opção de excluir tudo
			read op
			case $op in	
				y|yes)
					rm -r $project_path
					echo "The project has been deleted!"
				;;
				n|no)
					echo "The project folder hasn't been deleted!"
				;;
			esac
			
			
			opcao="Válida"
			;;
		n|no)
		
			;;
		v|view)
			tree $project_path
			echo ; echo "Local: $project_path"
			opcao="Inválida"
		;;
		*)
			echo "Invalid option!"
			opcao="Inválida"
		;;
	esac
done

echo "Done" ; echo
